begin;
set search_path = public, extensions, tests;
select plan(22);
select has_table('private', 'chat_request_quotas', 'quota table is private');
select is((select relrowsecurity from pg_class where oid='private.chat_request_quotas'::regclass), true, 'RLS enabled');
select is((select prosecdef from pg_proc where oid='public.consume_chat_quota()'::regprocedure), false, 'public wrapper is unprivileged');
select is((select proconfig from pg_proc where oid='private.consume_chat_quota()'::regprocedure), array['search_path=""'], 'privileged function has empty search path');
select is(has_function_privilege('anon', 'public.consume_chat_quota()', 'execute'), false, 'anonymous public execution revoked');
select is(has_function_privilege('anon', 'private.consume_chat_quota()', 'execute'), false, 'anonymous private execution revoked');
select tests.create_supabase_user('chat-owner@example.com') as owner \gset
select tests.create_supabase_user('chat-other@example.com') as other \gset
select tests.authenticate_as(:'owner'::uuid);
select is(public.consume_chat_quota(), true, 'first request allowed');
select is((select bool_and(public.consume_chat_quota()) from generate_series(1,9)), true, 'next nine requests allowed');
select is(public.consume_chat_quota(), false, 'eleventh request denied');
select throws_ok('select * from private.chat_request_quotas', '42501', null, 'quota rows cannot be read');
select throws_ok('update private.chat_request_quotas set minute_count=1', '42501', null, 'quota cannot be reset');
select throws_ok('delete from private.chat_request_quotas', '42501', null, 'quota cannot be deleted');
select tests.authenticate_as(:'other'::uuid);
select is(public.consume_chat_quota(), true, 'another account has its own quota');
select tests.clear_authentication();
set local role authenticated;
select is(public.consume_chat_quota(), false, 'missing identity fails closed');
set local role postgres;
update private.chat_request_quotas set minute_started=clock_timestamp()-interval '61 seconds' where user_id=:'owner'::uuid;
select tests.authenticate_as(:'owner'::uuid);
select is(public.consume_chat_quota(), true, 'minute window expires');
set local role postgres;
select is((select day_count from private.chat_request_quotas where user_id=:'owner'::uuid), 11, 'minute reset preserves daily count');
update private.chat_request_quotas set minute_count=1, day_count=99 where user_id=:'owner'::uuid;
select tests.authenticate_as(:'owner'::uuid);
select is(public.consume_chat_quota(), true, 'hundredth daily request allowed');
select is(public.consume_chat_quota(), false, 'hundred and first daily request denied');
set local role postgres;
update private.chat_request_quotas set day=(clock_timestamp() at time zone 'UTC')::date-1, minute_started=clock_timestamp()-interval '61 seconds' where user_id=:'owner'::uuid;
select tests.authenticate_as(:'owner'::uuid);
select is(public.consume_chat_quota(), true, 'next UTC day resets daily quota');
set local role postgres;
select is((select day_count from private.chat_request_quotas where user_id=:'owner'::uuid), 1, 'daily count restarts at one');
select tests.clear_authentication();
select throws_ok('select public.consume_chat_quota()', '42501', null, 'anonymous requests denied');
set local role postgres;
delete from auth.users where id=:'owner'::uuid;
select is_empty(format('select * from private.chat_request_quotas where user_id=%L', :'owner'), 'account deletion removes quota');
select * from finish();
rollback;
